
FROM ubuntu:zesty

MAINTAINER mliszcz<liszcz.michal@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    tree \
    build-essential \
    cmake \
    fuse \
    libtango-dev \
    libfuse-dev \
    libboost-all-dev
