
FROM fedora:25

MAINTAINER mliszcz<liszcz.michal@gmail.com>

RUN printf '[maxiv]\n\
name=MAX IV Public Repository for RHEL/CentOS $releasever - $basearch\n\
baseurl=http://pubrepo.maxiv.lu.se/rpm/fc23/$basearch/\n\
enabled=1\n\
gpgcheck=0\n\
'> /etc/yum.repos.d/maxiv.repo

RUN dnf -y install \
    git \
    which \
    hostname \
    tree \
    make \
    cmake \
    gcc \
    gcc-c++ \
    fuse \
    fuse-devel \
    libtango9-devel

RUN mkdir -p /usr/local/lib64 \
    && mkdir -p /usr/local/include \
    && git clone --depth 1 --branch release-1.8.0 \
        https://github.com/google/googletest \
    && mkdir -p googletest/build \
    && pushd googletest/build \
    && cmake .. \
    && make \
    && cp googlemock/libgmock* /usr/local/lib64/ \
    && cp googlemock/gtest/libgtest* /usr/local/lib64/ \
    && cp -r ../googlemock/include/* /usr/local/include/ \
    && cp -r ../googletest/include/* /usr/local/include/ \
    && popd \
    && rm -rf googletest
