#!/usr/bin/env bash

USER_UID=`id -u`
USER_GID=`id -g`

WORKDIR=`pwd`

docker run \
  -it \
  --net host \
  --privileged \
  --user "$USER_UID:$USER_GID" \
  --workdir "$WORKDIR" \
  -e HOME=$HOME \
  -v $HOME:$HOME \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  tango-fs-dev \
  /bin/bash
